import type { Loader, PluginBuilder } from 'bun'
import type { AutoImportsOptions, AutoImportsPlugin, ESLintOptions } from './types'
import { generateESLintGlobals } from './eslint'

function getLoader(path: string): string {
  return path.endsWith('ts')
    ? 'ts'
    : path.endsWith('js')
      ? 'js'
      : path.endsWith('tsx')
        ? 'tsx'
        : 'jsx'
}

const GENERATED_COMMENT = '// Generated by bun-plugin-auto-imports\n'

export function autoImports(options: Partial<AutoImportsOptions>): AutoImportsPlugin {
  return {
    name: 'bun-plugin-auto-imports',

    async setup(builder: PluginBuilder): Promise<void> {
      const { createUnimport } = await import('unimport')
      const { injectImports, generateTypeDeclarations } = createUnimport({
        ...options,
        dts: undefined,
      } as AutoImportsOptions)

      const dtsContent = await generateTypeDeclarations()
      // Add generated comment to d.ts file
      await Bun.write(
        options.dts ?? './auto-imports.d.ts',
        GENERATED_COMMENT + dtsContent,
      )

      if (options.eslint?.enabled === true) {
        const eslintOptions: ESLintOptions = {
          enabled: true,
          filepath: options.eslint.filepath ?? './.eslint-auto-import.json',
          globalsPropValue: options.eslint.globalsPropValue,
        }

        const eslintContent = generateESLintGlobals(dtsContent, eslintOptions)
        await Bun.write(eslintOptions.filepath ?? './auto-imports.d.ts', eslintContent)
      }

      builder.onLoad({ filter: /.*/ }, async (args) => {
        const fileContent = await Bun.file(args.path).text()
        const transformedFileContent = await injectImports(fileContent)

        return {
          contents: transformedFileContent.code,
          loader: getLoader(args.path) as Loader,
        }
      })
    },
  }
}

export default autoImports
